const QUANTUM_CITCUIT_BEGIN_COMPONENT_NAME = "Quantum_Circuit_Begin"
const EXPECTED_QUBITS = "expectedQubits"
const QUBITS_COMPONENT_NAME = "qbit"
const MEASURE_COMPONENT_NAME = "measure"
const SWAP_COMPONENT_NAME = "swap"


module.exports = {
    QUANTUM_CITCUIT_BEGIN_COMPONENT_NAME,
    EXPECTED_QUBITS,
    QUBITS_COMPONENT_NAME,
    MEASURE_COMPONENT_NAME,
    SWAP_COMPONENT_NAME
  };