const QUANTUM_CITCUIT_BEGIN_COMPONENT_NAME = "Quantum_Circuit_Begin"
const EXPECTED_QUBITS = "expectedQubits"
const QUBITS_COMPONENT_NAME = "qbit"


module.exports = {
    QUANTUM_CITCUIT_BEGIN_COMPONENT_NAME,
    EXPECTED_QUBITS,
    QUBITS_COMPONENT_NAME
  };