const QUANTUM_CITCUIT_BEGIN_COMPONENT_NAME = "Quantum_Circuit_Begin"
const EXPECTED_QUBITS = "expectedQubits"
const QUBITS_COMPONENT_NAME = "qbit"
const MEASURE_COMPONENT_NAME = "measure"
const SWAP_COMPONENT_NAME = "swap"
const CLASSICAL_REGISTER_COMPONENT_NAME = "Classical_register"
const QUANTUM_REGISTER_COMPONENT_NAME = "Quantum_register"


module.exports = {
    QUANTUM_CITCUIT_BEGIN_COMPONENT_NAME,
    EXPECTED_QUBITS,
    QUBITS_COMPONENT_NAME,
    MEASURE_COMPONENT_NAME,
    SWAP_COMPONENT_NAME,
    CLASSICAL_REGISTER_COMPONENT_NAME,
    QUANTUM_REGISTER_COMPONENT_NAME
  };