import_table = {
    "QISKIT_QUANTUM_CIRCUIT": "from qiskit import QuantumCircuit",
    "QISKIT_CLASSICAL_REGISTER": "from qiskit import ClassicalRegister",
    "QISKIT_QUANTUM_REGISTER": "from qiskit import QuantumRegister",
    "QISKIT_CIRCUIT_LIBRARY": "from qiskit.circuit.library import UGate",
    "QISKIT_AER_EXECUTE": "from qiskit import Aer, execute",
    "QISKIT_VISUALIZATION_HISTOGRAM": "from qiskit.visualization import plot_histogram",
    "QISKIT_SPARSE_PAULI_OP": "from qiskit.quantum_info import SparsePauliOp",
    "QISKIT_RESULT_QUASI_DISTRIBUTION": "from qiskit.result import QuasiDistribution",
    "QISKIT_ALGORITHMS_QAOA": "from qiskit_algorithms import QAOA",
    "QISKIT_ALGORITHMS_OPTIMIZERS": "from qiskit_algorithms.optimizers import {optimizer}",
    "NUMPY": "import numpy as np",
    "PYPLOT": "import matplotlib.pyplot as plt",
    "BASE64": "import base64",
    "IO": "import io",
    "WARNINGS": "import warnings",
    "NETWORKX": "import networkx as nx",
    "OS": "import os",
}

